Debug

diff --git a/Auto_Redis_Deploy/redis_install/redis_admin b/Auto_Redis_Deploy/redis_install/redis_admin
--- a/Auto_Redis_Deploy/redis_install/redis_admin
+++ b/Auto_Redis_Deploy/redis_install/redis_admin
@@ -26,7 +26,7 @@ install)
         if [ ! -e "${REDIS_URL##*/}" ]    
         then
              wget $REDIS_URL 
-             [ $? -ne 0 ] && echo "Unalbe to download Package from $REDIS_URL " && exit 0
+             [ $? -ne 0 ] && echo "Unable to download Package from $REDIS_URL " && exit 0
         fi
         ## Uncompress package
         if [ ! -d "${REDIS_URL##*/}" ]
